enum ExerciseType { weighted, bodyweight, timed }

class ExerciseDefinition {
  final String name;
  final ExerciseType type;

  const ExerciseDefinition(this.name, this.type);
}

class ExerciseLibrary {
  static const Map<String, List<ExerciseDefinition>> exercises = {
    'Chest': [
      ExerciseDefinition('Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Incline Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Decline Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Incline Dumbbell Press', ExerciseType.weighted),
      ExerciseDefinition('Decline Dumbbell Press', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Flyes', ExerciseType.weighted),
      ExerciseDefinition('Incline Dumbbell Flyes', ExerciseType.weighted),
      ExerciseDefinition('Cable Crossover', ExerciseType.weighted),
      ExerciseDefinition('Low Cable Crossover', ExerciseType.weighted),
      ExerciseDefinition('High Cable Crossover', ExerciseType.weighted),
      ExerciseDefinition('Pec Deck Machine', ExerciseType.weighted),
      ExerciseDefinition('Chest Press Machine', ExerciseType.weighted),
      ExerciseDefinition('Incline Chest Press Machine', ExerciseType.weighted),
      ExerciseDefinition('Wide Chest Press Machine', ExerciseType.weighted),
      ExerciseDefinition('Smith Machine Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Smith Machine Incline Press', ExerciseType.weighted),
      ExerciseDefinition('Landmine Press', ExerciseType.weighted),
      ExerciseDefinition('Svend Press', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Pullover', ExerciseType.weighted),
      ExerciseDefinition('Close Grip Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Seated Dip', ExerciseType.weighted),
    ],
    'Back': [
      ExerciseDefinition('Deadlift', ExerciseType.weighted),
      ExerciseDefinition('Romanian Deadlift', ExerciseType.weighted),
      ExerciseDefinition('Barbell Row', ExerciseType.weighted),
      ExerciseDefinition('Pendlay Row', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Row', ExerciseType.weighted),
      ExerciseDefinition('Seated Cable Row', ExerciseType.weighted),
      ExerciseDefinition('Wide Grip Cable Row', ExerciseType.weighted),
      ExerciseDefinition('T-Bar Row', ExerciseType.weighted),
      ExerciseDefinition('Lat Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Wide Grip Lat Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Reverse Grip Lat Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Single Arm Lat Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Straight Arm Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Hyperextension', ExerciseType.bodyweight),
      ExerciseDefinition('Good Morning', ExerciseType.weighted),
      ExerciseDefinition('Rack Pull', ExerciseType.weighted),
      ExerciseDefinition('Shrugs', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Shrugs', ExerciseType.weighted),
      ExerciseDefinition('Face Pull', ExerciseType.weighted),
      ExerciseDefinition('Reverse Fly', ExerciseType.weighted),
      ExerciseDefinition('Seated Reverse Fly', ExerciseType.weighted),
      ExerciseDefinition('Machine Row', ExerciseType.weighted),
      ExerciseDefinition('Machine Pulldown', ExerciseType.weighted),
      ExerciseDefinition('Low Row Machine', ExerciseType.weighted),
      ExerciseDefinition('Back Extension Machine', ExerciseType.weighted),
    ],
    'Shoulders': [
      ExerciseDefinition('Overhead Press', ExerciseType.weighted),
      ExerciseDefinition('Seated Overhead Press', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Shoulder Press', ExerciseType.weighted),
      ExerciseDefinition('Seated Dumbbell Press', ExerciseType.weighted),
      ExerciseDefinition('Arnold Press', ExerciseType.weighted),
      ExerciseDefinition('Lateral Raise', ExerciseType.weighted),
      ExerciseDefinition('Cable Lateral Raise', ExerciseType.weighted),
      ExerciseDefinition('Machine Lateral Raise', ExerciseType.weighted),
      ExerciseDefinition('Front Raise', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Front Raise', ExerciseType.weighted),
      ExerciseDefinition('Cable Front Raise', ExerciseType.weighted),
      ExerciseDefinition('Reverse Fly', ExerciseType.weighted),
      ExerciseDefinition('Cable Reverse Fly', ExerciseType.weighted),
      ExerciseDefinition('Upright Row', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Upright Row', ExerciseType.weighted),
      ExerciseDefinition('Smith Machine Overhead Press', ExerciseType.weighted),
      ExerciseDefinition('Machine Shoulder Press', ExerciseType.weighted),
      ExerciseDefinition('Behind the Neck Press', ExerciseType.weighted),
      ExerciseDefinition('Push Press', ExerciseType.weighted),
      ExerciseDefinition('Bradford Press', ExerciseType.weighted),
    ],
    'Biceps': [
      ExerciseDefinition('Barbell Curl', ExerciseType.weighted),
      ExerciseDefinition('EZ Bar Curl', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Curl', ExerciseType.weighted),
      ExerciseDefinition('Hammer Curl', ExerciseType.weighted),
      ExerciseDefinition('Incline Dumbbell Curl', ExerciseType.weighted),
      ExerciseDefinition('Concentration Curl', ExerciseType.weighted),
      ExerciseDefinition('Preacher Curl', ExerciseType.weighted),
      ExerciseDefinition('EZ Bar Preacher Curl', ExerciseType.weighted),
      ExerciseDefinition('Machine Preacher Curl', ExerciseType.weighted),
      ExerciseDefinition('Cable Curl', ExerciseType.weighted),
      ExerciseDefinition('Cable Hammer Curl', ExerciseType.weighted),
      ExerciseDefinition('Rope Hammer Curl', ExerciseType.weighted),
      ExerciseDefinition('Spider Curl', ExerciseType.weighted),
      ExerciseDefinition('Reverse Curl', ExerciseType.weighted),
      ExerciseDefinition('Reverse EZ Bar Curl', ExerciseType.weighted),
      ExerciseDefinition('Zottman Curl', ExerciseType.weighted),
      ExerciseDefinition('Cross Body Hammer Curl', ExerciseType.weighted),
      ExerciseDefinition('21s', ExerciseType.weighted),
      ExerciseDefinition('Cable Concentration Curl', ExerciseType.weighted),
      ExerciseDefinition('Machine Curl', ExerciseType.weighted),
    ],
    'Triceps': [
      ExerciseDefinition('Close Grip Bench Press', ExerciseType.weighted),
      ExerciseDefinition('Skull Crusher', ExerciseType.weighted),
      ExerciseDefinition('EZ Bar Skull Crusher', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Skull Crusher', ExerciseType.weighted),
      ExerciseDefinition('Tricep Pushdown', ExerciseType.weighted),
      ExerciseDefinition('Rope Pushdown', ExerciseType.weighted),
      ExerciseDefinition('V-Bar Pushdown', ExerciseType.weighted),
      ExerciseDefinition('Overhead Tricep Extension', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Overhead Extension', ExerciseType.weighted),
      ExerciseDefinition('Cable Overhead Extension', ExerciseType.weighted),
      ExerciseDefinition('Rope Overhead Extension', ExerciseType.weighted),
      ExerciseDefinition('EZ Bar Overhead Extension', ExerciseType.weighted),
      ExerciseDefinition('Tricep Kickback', ExerciseType.weighted),
      ExerciseDefinition('Cable Kickback', ExerciseType.weighted),
      ExerciseDefinition('Tate Press', ExerciseType.weighted),
      ExerciseDefinition('JM Press', ExerciseType.weighted),
      ExerciseDefinition('Smith Machine Skull Crusher', ExerciseType.weighted),
      ExerciseDefinition('Machine Tricep Extension', ExerciseType.weighted),
      ExerciseDefinition('Seated Overhead Extension', ExerciseType.weighted),
      ExerciseDefinition('Single Arm Pushdown', ExerciseType.weighted),
    ],
    'Legs': [
      ExerciseDefinition('Squat', ExerciseType.weighted),
      ExerciseDefinition('Front Squat', ExerciseType.weighted),
      ExerciseDefinition('Hack Squat', ExerciseType.weighted),
      ExerciseDefinition('Smith Machine Squat', ExerciseType.weighted),
      ExerciseDefinition('Bulgarian Split Squat', ExerciseType.weighted),
      ExerciseDefinition('Leg Press', ExerciseType.weighted),
      ExerciseDefinition('Narrow Stance Leg Press', ExerciseType.weighted),
      ExerciseDefinition('Wide Stance Leg Press', ExerciseType.weighted),
      ExerciseDefinition('Leg Extension', ExerciseType.weighted),
      ExerciseDefinition('Leg Curl', ExerciseType.weighted),
      ExerciseDefinition('Seated Leg Curl', ExerciseType.weighted),
      ExerciseDefinition('Lying Leg Curl', ExerciseType.weighted),
      ExerciseDefinition('Romanian Deadlift', ExerciseType.weighted),
      ExerciseDefinition('Stiff Leg Deadlift', ExerciseType.weighted),
      ExerciseDefinition('Good Morning', ExerciseType.weighted),
      ExerciseDefinition('Walking Lunge', ExerciseType.bodyweight),
      ExerciseDefinition('Reverse Lunge', ExerciseType.bodyweight),
      ExerciseDefinition('Side Lunge', ExerciseType.bodyweight),
      ExerciseDefinition('Step Up', ExerciseType.bodyweight),
      ExerciseDefinition('Hip Thrust', ExerciseType.weighted),
      ExerciseDefinition('Barbell Hip Thrust', ExerciseType.weighted),
      ExerciseDefinition('Glute Bridge', ExerciseType.bodyweight),
      ExerciseDefinition('Cable Kickback', ExerciseType.weighted),
      ExerciseDefinition('Donkey Kickback', ExerciseType.bodyweight),
      ExerciseDefinition('Calf Raise', ExerciseType.weighted),
      ExerciseDefinition('Seated Calf Raise', ExerciseType.weighted),
      ExerciseDefinition('Leg Press Calf Raise', ExerciseType.weighted),
      ExerciseDefinition('Sumo Squat', ExerciseType.weighted),
      ExerciseDefinition('Goblet Squat', ExerciseType.weighted),
      ExerciseDefinition('Box Squat', ExerciseType.weighted),
      ExerciseDefinition('Zercher Squat', ExerciseType.weighted),
      ExerciseDefinition('Sissy Squat', ExerciseType.bodyweight),
      ExerciseDefinition('Adductor Machine', ExerciseType.weighted),
      ExerciseDefinition('Abductor Machine', ExerciseType.weighted),
      ExerciseDefinition('Nordic Curl', ExerciseType.bodyweight),
    ],
    'Core': [
      ExerciseDefinition('Crunch', ExerciseType.bodyweight),
      ExerciseDefinition('Cable Crunch', ExerciseType.weighted),
      ExerciseDefinition('Machine Crunch', ExerciseType.weighted),
      ExerciseDefinition('Decline Crunch', ExerciseType.bodyweight),
      ExerciseDefinition('Oblique Crunch', ExerciseType.bodyweight),
      ExerciseDefinition('Bicycle Crunch', ExerciseType.bodyweight),
      ExerciseDefinition('Russian Twist', ExerciseType.bodyweight),
      ExerciseDefinition('Weighted Russian Twist', ExerciseType.weighted),
      ExerciseDefinition('Leg Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Hanging Leg Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Knee Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Hanging Knee Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Ab Wheel Rollout', ExerciseType.bodyweight),
      ExerciseDefinition('Dragon Flag', ExerciseType.bodyweight),
      ExerciseDefinition('Pallof Press', ExerciseType.weighted),
      ExerciseDefinition('Cable Woodchop', ExerciseType.weighted),
      ExerciseDefinition('Side Bend', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Side Bend', ExerciseType.weighted),
      ExerciseDefinition('Seated Twist', ExerciseType.bodyweight),
      ExerciseDefinition('Toe Touch', ExerciseType.bodyweight),
      ExerciseDefinition('V-Up', ExerciseType.bodyweight),
      ExerciseDefinition('Hollow Body Hold', ExerciseType.timed),
      ExerciseDefinition('Dead Bug', ExerciseType.bodyweight),
      ExerciseDefinition('Bird Dog', ExerciseType.bodyweight),
      ExerciseDefinition('Windshield Wiper', ExerciseType.bodyweight),
      ExerciseDefinition('Total Abdominal', ExerciseType.weighted),
      ExerciseDefinition('Standing Crunch', ExerciseType.weighted),
      ExerciseDefinition('Bench Crunch', ExerciseType.bodyweight),
    ],
    'Forearms': [
      ExerciseDefinition('Wrist Curl', ExerciseType.weighted),
      ExerciseDefinition('Reverse Wrist Curl', ExerciseType.weighted),
      ExerciseDefinition('Barbell Wrist Curl', ExerciseType.weighted),
      ExerciseDefinition('Dumbbell Wrist Curl', ExerciseType.weighted),
      ExerciseDefinition('Behind Back Wrist Curl', ExerciseType.weighted),
      ExerciseDefinition('Reverse Curl', ExerciseType.weighted),
      ExerciseDefinition('Forearm Hammer Curl', ExerciseType.weighted),
      ExerciseDefinition('Zottman Curl', ExerciseType.weighted),
      ExerciseDefinition('Farmer Walk', ExerciseType.weighted),
      ExerciseDefinition('Plate Pinch', ExerciseType.timed),
      ExerciseDefinition('Towel Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Fat Grip Curl', ExerciseType.weighted),
      ExerciseDefinition('Wrist Roller', ExerciseType.weighted),
      ExerciseDefinition('Finger Extension', ExerciseType.bodyweight),
      ExerciseDefinition('Grip Squeezer', ExerciseType.timed),
    ],
    'Bodyweight': [
      ExerciseDefinition('Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Wide Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Diamond Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Decline Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Incline Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Pike Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Archer Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Wide Grip Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Chin Up', ExerciseType.bodyweight),
      ExerciseDefinition('Neutral Grip Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Ring Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Muscle Up', ExerciseType.bodyweight),
      ExerciseDefinition('Dip', ExerciseType.bodyweight),
      ExerciseDefinition('Ring Dip', ExerciseType.bodyweight),
      ExerciseDefinition('Bench Dip', ExerciseType.bodyweight),
      ExerciseDefinition('Plank', ExerciseType.timed),
      ExerciseDefinition('Side Plank', ExerciseType.timed),
      ExerciseDefinition('Hollow Body Hold', ExerciseType.timed),
      ExerciseDefinition('L-Sit', ExerciseType.timed),
      ExerciseDefinition('Tuck L-Sit', ExerciseType.timed),
      ExerciseDefinition('Dead Hang', ExerciseType.timed),
      ExerciseDefinition('Pistol Squat', ExerciseType.bodyweight),
      ExerciseDefinition('Jump Squat', ExerciseType.bodyweight),
      ExerciseDefinition('Burpee', ExerciseType.bodyweight),
      ExerciseDefinition('Mountain Climber', ExerciseType.bodyweight),
      ExerciseDefinition('Jumping Jack', ExerciseType.bodyweight),
      ExerciseDefinition('Box Jump', ExerciseType.bodyweight),
      ExerciseDefinition('Broad Jump', ExerciseType.bodyweight),
      ExerciseDefinition('Handstand Hold', ExerciseType.timed),
      ExerciseDefinition('Handstand Push Up', ExerciseType.bodyweight),
      ExerciseDefinition('Inverted Row', ExerciseType.bodyweight),
      ExerciseDefinition('Australian Pull Up', ExerciseType.bodyweight),
      ExerciseDefinition('Tuck Planche', ExerciseType.timed),
      ExerciseDefinition('Front Lever', ExerciseType.timed),
      ExerciseDefinition('Back Lever', ExerciseType.timed),
      ExerciseDefinition('Human Flag', ExerciseType.timed),
      ExerciseDefinition('Nordic Curl', ExerciseType.bodyweight),
      ExerciseDefinition('Glute Bridge', ExerciseType.bodyweight),
      ExerciseDefinition('Hip Thrust', ExerciseType.bodyweight),
      ExerciseDefinition('Superman', ExerciseType.bodyweight),
      ExerciseDefinition('Reverse Hyperextension', ExerciseType.bodyweight),
      ExerciseDefinition('Hanging Leg Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Knee Raise', ExerciseType.bodyweight),
      ExerciseDefinition('Toes to Bar', ExerciseType.bodyweight),
      ExerciseDefinition('Sit Up', ExerciseType.bodyweight),
      ExerciseDefinition('V-Up', ExerciseType.bodyweight),
      ExerciseDefinition('Flutter Kick', ExerciseType.bodyweight),
      ExerciseDefinition('Scissor Kick', ExerciseType.bodyweight),
    ],
  };

  static List<String> get muscleGroups => exercises.keys.toList();

  static List<ExerciseDefinition> getExercises(String muscleGroup) =>
      exercises[muscleGroup] ?? [];

  static ExerciseType getType(String muscleGroup, String name) {
    final list = exercises[muscleGroup] ?? [];
    return list
        .firstWhere((e) => e.name == name,
            orElse: () => ExerciseDefinition(name, ExerciseType.weighted))
        .type;
  }
}
